# Site settings
title: B&B 2016
email: info@bikeandbuild.org
author: Alex Bloom
description: > # this means to ignore newlines until "baseurl:"
  Bike And Build 2016 Annual Report
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

sass:
    style: compressed

# Build settings
markdown: kramdown

# Exclusions from Build
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - .sass-cache
# exclude: [gulpfile, .sass-cache]
